#!/usr/bin/env bash

# This script generates the graticules. The steps are:
# 1. Generate standard graticule (cartesian grid)
# 2. Project the graticule on the appropriate projection
# 3. Use octave for drawing the graticule on a svg file
# 4. Change the name of the file grat.svg and move it to the images folder
# 5. Merge manually with the topographic data using Inkscape


./std_graticule.py 1 > grat.dat

./projectgrat.py pc
./oct
mv gratpj.svg platecarre.svg

./projectgrat.py gallpeters
./oct
mv gratpj.svg gallpeters.svg

./std_graticule.py 4 > grat.dat

./projectgrat.py mollweide
./oct
mv gratpj.svg mollweide.svg

./projectgrat.py aziequi
./oct
mv gratpj.svg aziequi.svg

# gnomonic needs manual ajdustments and a more fine graticule
./std_graticule.py 4 > grat.dat
./projectgrat_gnomo.py
./oct
mv gratpj.svg gnomo.svg

# mercator needs its own graticule (maxlat = 82)
./std_graticule_merc.py > grat.dat
./projectgrat.py merc
./oct
mv gratpj.svg mercator.svg


rm grat.dat
rm gratpj.dat
mv *.svg ../images/


